### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Senior_design_ui)
add_subdirectory(Senior_design_uiContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Senior_design_uiplugin
    Senior_design_uiContentplugin
    QtQuickDesignerComponents)